# Generated by Django 6.0.7 on 2026-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='XYN ARTS', max_length=50)),
                ('subtitle', models.CharField(default='PORTFOLIO', max_length=50)),
                ('icon', models.CharField(default='✦', max_length=50)),
                ('role_line1', models.CharField(default='DIGITAL', max_length=30)),
                ('role_line2', models.CharField(default='ILLUSTRATOR', max_length=30)),
                ('banner', models.ImageField(blank=True, upload_to='banner/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
