# Generated by Django 6.0.7 on 2026-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(default='ABOUT ME', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_signature',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(default=''),
        ),
    ]
